apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs3
spec:
 replicas: 3
 selector:
   matchLabels:
     app: nodejs-app3
 template:
   metadata:
     labels:
       app: nodejs-app3
   spec:                  
     containers:
     - name: nodejs-app3
       image: vigneshvicky12345/node-app:latest
       ports:
       - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  type: NodePort
  selector:
    app: nodejs-app
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
